site_name: Slowist's Note
site_url: https://slowist-lee.github.io/notebook/
theme:
  name: material
  custom_dir: overrides
  icon:
    logo: material/book
  favicon: images/favicon.png
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: cyan
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  font: false
    # code: JetBrains Mono
  # icon:
    # logo: assets/logo.png
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.path
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
repo_url: https://github.com/Slowist-Lee/notebook
repo_name: Slowist/Notebook
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Slowist-Lee/slowist-notebook
    - icon: fontawesome/regular/envelope 
      link: mailto:<leexin005@163.com> 

  feedback:
    title: 此页面有帮助吗？
    ratings:
      - icon: material/thumb-up-outline
        name: This page was helpful
        data: 1
        note: >-
          谢谢你的反馈！
      - icon: material/thumb-down-outline
        name: This page could be improved
        data: 0
        note: >-
          Thanks for your feedback! Help us improve this page by
          using our <a href="https://marketingplatform.google.com/about/analytics/" target="_blank" rel="noopener">feedback form</a>.

plugins:
  - search
  - statistics
  - git-revision-date-localized:
      enable_creation_date: true
  - toc
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - mdx_truly_sane_lists
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight: # 代码块高亮
      auto_title: true # 显示编程语言名称
extra_javascript:
  - js/katex.js
  - js/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://cdn.tonycrane.cc/jbmono/jetbrainsmono.css
  - https://cdn.tonycrane.cc/lxgw/lxgwscreen.css
  - stylesheets/extra.css
  - https://unpkg.com/katex@0/dist/katex.min.css

copyright: Copyright &copy; Slowist/All Rights Reserved. # 左下角的版权声明

nav:
  - index.md
  - Computer Science:
    - cs/index.md
    - Language:
      - C:
        - cs/pl/C/index.md
        - Ch7 Pointer: cs/pl/C/Pointer.md
        - Ch8 String: cs/pl/C/String.md
        - Ch9 Structure: cs/pl/C/Structure.md
        - Misc: cs/pl/C/misc.md
      - Asm:
        - cs/pl/Asm/index.md
        - Misc: cs/pl/Asm/Misc.md
    - Algorithm:
      - cs/algorithm/index.md
      - cs61b:
        - Lecture1 Introduction: cs/algorithm/cs61b/Lecture1_Introduction.md
        - Lecture2 Defining and Using Classes: cs/algorithm/cs61b/Lecture2_Defining and Using Classes.md
        - Lecture3 ListsI References Recursion and Lists: cs/algorithm/cs61b/Lecture3_ListsI_References_Recursion_and_Lists.md
  - AI:
    - AI/index.md
    - Computer Vision:
        - Introduction to CV:
          - Lecture 1: AI/Computer Vision/Introduction to CV/Lecture 1.md
  - Math: 
    - Math/index.md
    - 复变函数与积分变换: Math/complex.md
    - 概率论与数理统计: Math/Probability/Error.md
    - 数学建模: 
      - Math/MathModel/index.md
      - Note: 
        - 1. 数学规划: Math/MathModel/note/program/program.md
        - 2. 图论模型: Math/MathModel/note/graph/graph.md
      - Test:
        - 24-25秋冬期末(ACEE): Math/MathModel/test/index.md
  - ISEE: 
    - isee/index.md
    - 模电(电基 ver.): 
      - isee/Analog/index.md
      - BJT:
        - isee/Analog/bjt/index.md
      - MOS:
        - isee/Analog/MOS/index.md
      - 多级、差分:
        - isee/Analog/Hard/index.md
      - 运算放大器:
        - isee/Analog/opam/index.md
      - 频率响应:
        - isee/Analog/freq/index.md
      - 反馈:
        - isee/Analog/feedback/index.md
      - 功率放大器:
        - isee/Analog/pa/index.md
  - English:
    - English/index.md
    - Interpretation: 
      - English/Interpretation/index.md
      - 学习体验:
        - English/Interpretation/experience/Harvest.md
        - English/Interpretation/experience\Interpretation--Self Assessment.md
      - HW && Topic: 
        - English/Interpretation/homework/Welcome Speech.md
        - English/Interpretation/homework/City and Travel.md
        - English/Interpretation/homework/Culture and Education.md
        - English/Interpretation/homework/Science.md
      - Learning Resources:
        - English/Interpretation/homework/Material.md
  - Others: 
    - Others/index.md
    - Others/雕版印刷与刻本文化.md
  - Writings:
    - Writings/index.md
    - Essay:
      - 一：当回想起IAI: Writings/essay/01.md
      - 二：带论的碎碎念: Writings/essay/02.md
      - 五：支教流水账: Writings/essay/05.md
      - 八：About Slowist: Writings/essay/08.md
      - 十：ACEE报名体验: Writings/essay/10.md
      - 十一：About IAI: Writings/essay/11.md
      - 十二：大一回忆录: Writings/essay/12.md
      - 十三：分流建议: Writings/essay/13.md
      - 十四：转专业路上的碎碎念: Writings/essay/14.md
    - Emotion:
      - 三: Writings/emotion/03.md
      - 四: Writings/emotion/04.md
      - 六: Writings/emotion/06.md
      - 七: Writings/emotion/07.md  
      - 九: Writings/emotion/09.md


    